#+title: ブログを書くためのストック

ブログを書きたいと思ったネタや書いている最中のドラフトの一時避難場所

inbox + memorandom

* ブログやアウトプットに関してのメモ

** MemoとDocument

* 書きたい/書いてみたいこと

** 統計オタク・統計（笑）のように言われることに対して
データデータデータと言われるようになって
データは何か特別なインサイトや発見、まだ見ぬ新法則を発見するようなものではない。
現状の実情を把握するだけものである。
では、なぜデータを使う必要があるのかという問いに関していえば、
客観的な判断が必要であるからであり、
統計をはじめとする手法を使うのは、その判断に必要な情報の取捨選択に対しても
主観的な判断を行うのではなく、客観的に判断をする必要があるからである。


** アイディアの作り方 / 評価の仕方
- idea = identy (調べる)
  ideaをidentityと考えてみると、Apple, Googleは世界に対して強いidentityを示している。 
  強いidentityは世界の課題を解決し、それが普遍的なものであるほど、強い課題になる。
  - Apple: だれでも使える携帯、ギークなイメージがないPC
  - Google：情報の正しさ
  課題を解決したものが強いidentityを示し、それは強いideaによって、成り立っている。
  普遍的な課題、誰も解決していない課題、多くの事象が混み合った課題、などがある。 それを解決するのが、
  アイディアである。解決の仕方によって陳腐なものから、革新的なものまであるが、 
  その課題を解決できているかどうかが最も重要視されるべきでは
- アイディアを作る時は、必要十分条件をしっかりと列挙すること。制約・制限条件


** マーケティングにおけるKPIの設定に関して
マーケティングプロモーション、特に広告においては消費者側にどのようなイメージを残しておくかだけが大事
認知->興味や関心->意向->購買のように移ることを目的とするわけではない。
どのようなイメージ・ブランドを残存させるべきなのかを考える必要がある。
認知したあと、そのイメージをどう残し続けるか。また、その商品やプロダクトに対して情報を取得する・しやすい場所があるから、
そこに接点を作っておく


** 因子分析に関するブログ
*** 因子分析をRで行うためのサマリーコードと手順
1. はじめに
2. pre因子分析 サンプル数とKMOによるサンプリングによる適切性指標
3. 相関係数の種類
4. 因子数の決定 -ガットマン基準と平行分析
5. 回転方法に関して -直行：〇〇、斜行：〇〇
6. 因子分析の結果の可視化
7. 因子得点の推定方法


*** 因子分析を行う前の因子抽出の適切性に関する深掘り 
- [ ]  バートレットの球面生検定 主成分・因子分析の相関行列が単位行列である（主成分・因子分析の実行が不適切である）という帰無仮説に対して実施する検定
   参考：[[https://bookdown.org/sbtseiji/jamovi_quickguide_J/sec-factor-efa.html][6.3 Exploratory Factor Analysis（探索的因子分析） | jamoviクイックガイド（Analysis編）]]
 
- [ ] 反イメージ相関行列 / anti-image correlation matrix
  - 因子分析が有効であるためには、変数間の相関係数の絶対値がある程度大きくなければならない。
  - 小さな相関係数が多いと共通因子があるという仮定がしにくいためである。
 	変数間の相関関係の強さは偏相関係数で判定することができる。
  - 変数が共通因子を持つ場合は変装間係数は小さくなるため、偏相関係数の符号を逆転したものは
    反イメージ相関係数と呼ばれ、この値が０に近い時は因子分析が有効であることを示すが、
    そうでない場合は因子分析が良好でないとする。
 	参考：[[https://www.ibm.com/support/knowledgecenter/fi/SSLVMB_sub/statistics_mainhelp_ddita/spss/base/idh_fact_des.html][IBM Knowledge Center]]
  - 良好な因子モデルでは、対角要素以外のほとんどの要素が小さい値になり、
    変数に対する妥当性の指標は、反イメージ相関行列の対角に示される。
 	参考：[[http://aoki2.si.gunma-u.ac.jp/lecture/PFA/pfa6.html][相関係数行列の吟味]]
  - イメージ分析：対角線上にある値が1に近いほどよく、0.50以上で妥当な値となる。
 
  - KMOの結果に加えて、各変数を因子分析に加えていいかどうかをはかる。
    検証：KMO(data)$ImgCovと ppcor::pcor(data)で結果を比較
    

*** 因子分析を行うための相関係数
- 量的な変数同士の相関係数 → ピアソンの相関係数
- 質的な変数同士であり、片方の変数のカテゴリの数が3種類以上である場合 → ポリコリック相関係数 ~polychor()~
- 質的な変数同士であり、両方の変数のカテゴリ数が2種類である場合 → テトラコリック相関係数 ~psych::tetrachoric()~
- 質的な変数と量的な変数の組み合わせで、質的な変数が2つのとき → バイシリアル相関係数 ~polycor::~
- 質的な変数と量的な変数の組み合わせで、質的な変数が3つ以上のとき → ポリシリアル相関係数 ~polycor::polyserial~

#+begin_src R 
data <- data.frame(
  x = c(1, 1, 2, 2, 1, 3, 3, 3, 1, 1),
  y = c(3, 3, 1, 1, 2, 2, 2, 1, 2, 2)
  )

# - pearson corr
print(paste0("peason cor: ", cor(data$x,data$y)))
 
# - polychoric
print(paste0("polychor cor: ", polychor(data$x,data$y)))
#  polychor(data$x, data$y,ML=TRUE)
data <- data.frame(
  x = c(0,1,0,1,1,0,1,1),
  y = c(1,0,0,1,0,0,1,1),
  z = c(0,0,0,1,0,0,0,0),

)
 
# - tetrachoric
print(paste0("tetrachoric cor: ", tetrachoric(data)))
# - byserial
 
# - polyserial
## polyserial(x,y)
 
#+end_src


*** 因子数決定方法に関して
- MAPテスト
- VSS基準
- スクリープロット
- SMC
- 平行分析


*** 回転方法に関する深掘り
回転がなぜ必要なのかに関して


*** 因子得点に関する深掘り
- サーストン
- バートレット
- アンダーソンとルービン
- ハーマン
- tenBerge


*** 推定結果の妥当性と信頼性
**** クロンバックのα係数

**** 信頼区間

**** 残差相関行列

**** 共通性とSMCの比較



** 主成分分析に関するブログ
   - [ ]
   - [ ] 
  

** 次元圧縮の手法に関して
   主成分分析やMDSをはじめとした、各種の次元圧縮の特徴と差の検証
   参考：
   - [[https://github.com/kyoustat/rdimtools][kyoustat/Rdimtools: Dimension Reduction and Estimation Methods]]
   - 


** GEEモデルに関して

   参考:
   - [[https://www.andrewheiss.com/blog/2021/01/15/msm-gee-multilevel/][Marginal structural models for panel data with GEE and multilevel models | Andrew Heiss]]


** ランダム効果モデルに関して
   参考：
   - [[https://sam-portnow.netlify.app/post/2020-12-15/][Random Effects Model From Scratch - Sam Portnow's Blog]]


** Rできれいなクロス集計表を作成する方法

*** gtを使った方法
- cell_bordersに関してまとめる

*** flextableを使った方法

*** kableを使った方法


** shinyのフレームワークのスニペットをまとめてみたい

*** shinydashboard

*** shinymaterial

*** 


** 

* 本・論文のメモ
** 
** 

* 仕事・アイディア・マーケティングに関する考え方のメモ

** 自分が思うマーケティングプランの作り方に関してまとめてみる


* マーケティング・ビジネスの事例メモ

** 


* 仕事やモチベーションを高める言葉

** 

* 愚痴・ミスについて書いておく。イライラをなくすために
** ミス
** 
